### ISSUE TITLE
Conflicting udev rule between groovy and hydro package

### ISSUE THREAD

**Issue by dgossow** [ros-visualization/oculus_sdk#1]
When installing oculus-sdk for groovy and hydro, you get this message:

```
Unpacking ros-groovy-oculus-sdk (from .../ros-groovy-oculus-sdk_0.2.3-0precise-20130815-0108-+0000_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/ros-groovy-oculus-sdk_0.2.3-0precise-20130815-0108-+0000_amd64.deb (--unpack):
 trying to overwrite '/etc/udev/rules.d/90-oculus.rules', which is also in package ros-hydro-oculus-sdk 0.2.3-4precise-20130808-0743-+0000
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ros-groovy-oculus-sdk_0.2.3-0precise-20130815-0108-+0000_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

You could just change the file name so they don't conflict between the packages, but is there a good way to solve this? @tfoote

**Comment by tfoote** [comment]
I think there's a way to make it a configuration file somehow in the
control/rules file such that it will detect that the other one is already
there and be ok with it. I'm not sure how to do that properly though.

The cleanest solution would be to make it distro independent as that's what
it really is, but I don't want to couple the distros like that.
