### ISSUE TITLE
oculus_sdk does not install package.xml

### ISSUE THREAD

**Issue by cottsay** [ros-visualization/oculus_sdk#2]
REP 136 (http://www.ros.org/reps/rep-0136.html) states that all packages should install a `package.xml` if released into ROS, and `oculus_sdk` does not do this.

Please add a Bloom patch to add the following line (or something similar) to the end of your `CMakeLists.txt`, as instructed in http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty#Adding_an_Install_Rule_as_a_Patch:

``` cmake
install(FILES package.xml DESTINATION share/oculus_sdk)
```

See also https://github.com/ros/catkin/issues/622

Thanks!

**Comment by dgossow** [comment]
@tfoote I patched the CMakeLists.txt but this needs to be re-released. Don't know how to go forward with the versioning and so on, and since this is a non catkin package. Could you take a look at this?

**Comment by clalancette** [comment]
Closing this old issue to archive the repository.
