### ISSUE TITLE
sdk 0.3

### ISSUE THREAD

**Issue by fredinhuf** [ros-visualization/oculus_sdk#4]
Hey guys, is there a package for newer versions of the sdk supporting DK2?

**Comment by ZdenekM** [comment]
+1 for DK2 support

**Comment by fredrabelo** [comment]
@ZdenekM hey, you can find an updated version here:

https://github.com/jherico/OculusSDK

**Comment by rebhuhnd** [comment]
@ZdenekM
@fredinhuf
I made one [here](https://github.com/OSUrobotics/ros_ovr_sdk) for 0.5.0.1 and beyond, though it's mostly geared for C++ stuff.

**Comment by clalancette** [comment]
Closing this old issue to archive the repository.
